# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from get_otp import get_otp_code
import os
import time

class SSO_SIGN():
  def setup_method(self):
    self.chrome_options = webdriver.ChromeOptions()
    self.chrome_options.add_argument("--headless")
    self.chrome_options.add_argument("--disable-gpu")
    
    if os.name != 'nt':
      self.chrome_options.add_argument("--no-sandbox")
      self.chrome_options.add_argument("--disable-dev-shm-usage")
    
    self.driver = webdriver.Chrome(service=Service(), options=self.chrome_options)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()

  def close_windows(self):
    self.driver.close()

  def action(self, url, otp_key, username, passwd):
    self.setup_method()
    self.driver.get(url)
    self.driver.implicitly_wait(60)
    print("authorization page load success")
    self.driver.set_window_size(1278, 1391)
    self.driver.find_element(By.ID, "cli_verification_btn").click()
    self.driver.implicitly_wait(60)
    print("name input page load success")
    self.driver.find_element(By.ID, "awsui-input-0").clear()
    self.driver.find_element(By.ID, "awsui-input-0").click()    
    self.driver.find_element(By.ID, "awsui-input-0").send_keys(username)
    self.driver.find_element(By.CSS_SELECTOR, ".awsui-button").click()
    self.driver.implicitly_wait(60)
    print("name paste and click success")
    print("password input page load success")
    self.driver.find_element(By.ID, "awsui-input-1").click()
    self.driver.find_element(By.ID, "awsui-input-1").send_keys(passwd)
    self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-variant-primary").click()
    self.driver.implicitly_wait(60)
    print("password paste and click success")
    print("otp input page load success")
    print("get otp code process")
    otp_code = get_otp_code(otp_key)
    print("get otp code success")
    self.driver.find_element(By.ID, "awsui-input-2").click()
    self.driver.find_element(By.ID, "awsui-input-2").send_keys(otp_code)
    self.driver.find_element(By.CSS_SELECTOR, ".awsui-button-variant-primary > span").click()
    self.driver.implicitly_wait(60)
    print("otp code paste and click success")
    print("allow click page load success")
    self.driver.find_element(By.ID, "cli_login_button").click()
    self.driver.implicitly_wait(60)
    print("allow click success")
    time.sleep(5)
    self.close_windows()
